adobe/fastly-native-promises

- .gitignore
- README.md
- README.md.hbs
- package-lock.json
- package.json
- src/index.js
Use jsdoc-to-markdown to automatically update the README.md with full API documentation
> WIP: Automatically generate documentation

- README.md
- src/index.js
- test/activateVersion.default.test.js
- test/cloneVersion.default.test.js
- test/getVersions.test.js
- test/response/activateVersion.response.js
- test/response/cloneVersion.response.js
- test/response/readVersions.response.js
> Better default versions

- README.md
- src/httpclient.js
- src/index.js
- test/createDictionary.test.js
- test/deleteDictionary.test.js
- test/readDictItems.test.js
- test/readDictionaries.test.js
- test/readDictionary.test.js
- test/response/dictionary.response.js
- test/response/dictitem.response.js
- test/updateDictionary.test.js
- test/writeDictItem.create.js
- test/writeDictItem.delete.js
- test/writeDictItem.noop.js
- test/writeDictItem.update.js
> Implement full support for dicts

- package-lock.json
- package.json
- src/httpclient.js
- src/index.js
- test/httpclient.test.js
- test/readDictionary.test.js
- test/readS3.401.test.js
- test/readS3.404.test.js
> More Robustness for GET Requests

- README.md
- README.md.hbs
- package-lock.json
- package.json
- src/conditions.js
- src/index.js
- test/conditions.update.test.js
- test/createCondition.test.js
- test/deleteCondition.test.js
- test/readCondition.test.js
- test/readConditions.test.js
- test/response/condition.response.js
- test/updateCondition.test.js
Adds support for listing, reading, creating, updating, and deleting conditions
fixes #34
> feat(fastly): Support CRUD operations on conditions

- package-lock.json
- package.json
[Issue #53: Greenkeeper/eslint plugin jsdoc 4.8.0](https://github.com/adobe/fastly-native-promises/issues/53)
> Greenkeeper/eslint plugin jsdoc 4.8.0

- package-lock.json
- package.json
> Greenkeeper/eslint plugin jsdoc 7.0.2

- package-lock.json
- package.json
> Greenkeeper/mocha parallel tests 2.1.1

- package-lock.json
- package.json
> Greenkeeper/eslint plugin jsdoc 7.2.3

- package-lock.json
- package.json
> Greenkeeper/mocha parallel tests 2.2.0

- src/api-acount.js
- src/api-auth.js
- src/httpclient.js
- src/index.js
- test/acceptInvitation.test.js
- test/createInvitation.test.js
- test/createToken.test.js
- test/createUser.test.js
- test/deleteInvitation.test.js
- test/deleteToken.test.js
- test/readCurrentUser.test.js
- test/readCustomerTokens.test.js
- test/readInvitations.test.js
- test/readSelfToken.test.js
- test/readService.test.js
- test/readServiceDomains.test.js
- test/readServicesById.test.js
- test/readToken.test.js
- test/readTokens.test.js
- test/readUser.test.js
- test/readUsers.test.js
- test/response/readInvitations.response.js
- test/response/readUser.response.js
- test/response/readUsers.response.js
- test/response/tokens.response.js
> Add more functions

- package-lock.json
- package.json
> Greenkeeper/eslint plugin jsdoc 8.3.2

- package-lock.json
- package.json
> Greenkeeper/eslint plugin jsdoc 8.4.0

- package-lock.json
- package.json
> Greenkeeper/eslint plugin jsdoc 9.0.1

- package-lock.json
- package.json
> Greenkeeper/eslint plugin jsdoc 15.3.4

- package-lock.json
- package.json
> Greenkeeper/commitizen 4.0.1

- package-lock.json
- package.json
> Greenkeeper/mocha parallel tests 2.2.2

- src/api-domain.js
- src/index.js
- test/createDomain.test.js
- test/deleteDomain.test.js
- test/domainCheck.test.js
- test/readDomain.test.js
- test/response/createDomain.response.js
- test/response/domainCheck.response.js
- test/response/readDomain.response.js
- test/response/updateDomain.response.js
- test/updateDomain.test.js
- moves existing _domain_ functions to new `DomainAPI` class
- add more domain related functions like: `createDomain`, `updateDomain` and `deleteDomain`
> feat(domain): add more domain functions

- package-lock.json
- package.json
> Greenkeeper/nock 11.3.2

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- README.md.hbs
CONTRIBUTING, CODE_OF_CONDUCT and README were amended to add in a number of missing punctuation within said documents.
No related issue.
> docs: Corrected a number of missing punctuation issues in docs

- package-lock.json
- package.json
> Greenkeeper/eslint plugin jsdoc 15.9.10

- README.md
- src/api-healthcheck.js
- src/index.js
- test/createHealthcheck.test.js
- test/deleteHealthcheck.test.js
- test/readHealthcheck.test.js
- test/readHealthchecks.test.js
- test/response/createHealthcheck.response.js
- test/response/deleteHealthcheck.response.js
- test/response/readHealthcheck.response.js
- test/response/readHealthchecks.response.js
- test/response/updateHealthcheck.response.js
- test/updateHealthcheck.test.js
Closes https://github.com/adobe/fastly-native-promises/issues/7
> Add healthcheck methods

- README.md
docs (readme.md) : change in spelling, grammar, punctuation
-change in the required punctuation, grammar, spellings as needed
Closes #125 
> docs (readme.md) : change in spelling, grammar, punctuation  -change in the required punctuation, grammar, spellings as needed  Closes #125

- src/index.js
Fixes #172 
Adds a `readSnippets` method
> add readSnippets method

- package-lock.json
- src/index.js
- test/edgedict.integration.test.js
> fix(dicts): urlencode dict keys

- README.md
- src/index.js
> feat(logging): add support for HTTPS log streaming API

- src/httpclient.js
- src/lock.js
- test/lock.test.js
> No concurrent modifications

- src/index.js
> feat(healthcheck): add writeHealthcheck method for upserts

- src/httpclient.js
> fix(http): retry in case of timeouts

- src/index.js
- test/headers.update.test.js
> fix(index): retry with POST after failed PUT

- src/index.js
- test/conditions.integration.test.js
> Integration test for conditions

- src/httpclient.js
There are currently duplicate request headers, differing by case only, sent by the http client. Resulting in `content-type: application/json, application/json` being sent over the wire. 
This PR fixes this  by normalizing headers using a `Headers` instance.
> fix: normalize headers

- src/httpclient.js
> feat(http): add more detailed error reporting on abort errors

- src/index.js
> feat(index): allow timeouts to be configurable

- README.md
- README.md.hbs
- src/httpclient.js
- src/index.js
- test/constructor.test.js
> fix: discard() is async

- package-lock.json
- package.json
> fix(deps): bump helix-fetch

- src/index.js
- test/createResponse.test.js
- test/deleteResponse.test.js
- test/readResponse.test.js
- test/readResponses.test.js
- test/response/response.response.js
- test/updateResponse.test.js
> feat(responses): add CRUD support for synthetic responses

- src/httpclient.js
> fix: clear timeout after use

- package-lock.json
- package.json
- src/httpclient.js
> fix: @adobe/helix-fetch -> @adobe/fetch

- CONTRIBUTING.md
- README.md
- test/package.integration.test.js
> Alt fastly svc

- renovate.json
> chore(renovate): allow forks
